---
title: "PLS analysis results"
author: "Luke W. Johnston"
date: "`r Sys.Date()`"
output: 
    rmarkdown::html_vignette:
        toc: true
        fig_width: 6
        fig_height: 6
vignette: >
  %\VignetteIndexEntry{PLS analysis results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Setup

```{r setup}
devtools::load_all()
library(pls)
```

# PLS for HOMA

```{r homa}
fit_train <- project_data %>%
    analyze_pls(y = 'lHOMA2_S')

ds <- project_data %>% 
    prep_gee_pls_data(
        analyze_pls(project_data, y = 'lHOMA2_S', cv = FALSE)
        )

plot(x = ds$Comp1, y = ds$lHOMA2_S)    
plot(x = ds$Comp2, y = ds$lHOMA2_S)    

summary(fit_train)
validationplot(fit_train, newdata = fit_train$test_data)
predplot(fit_train, ncomp = c(1,2), newdata = fit_train$test_data)
plot_pls(fit_train)
calc_pred_corr(fit_train, fit_train$test_data)
```

# PLS for ISI

```{r isi}
fit_train <- project_data %>%
    analyze_pls(y = 'lISI')

ds <- project_data %>% 
    prep_gee_pls_data(
        analyze_pls(project_data, y = 'lISI', cv = FALSE)
        )

plot(x = ds$Comp1, y = ds$lISI)    
plot(x = ds$Comp2, y = ds$lISI)    

summary(fit_train)
validationplot(fit_train, newdata = fit_train$test_data)
predplot(fit_train, ncomp = c(1,2), newdata = fit_train$test_data)
plot_pls(fit_train)
calc_pred_corr(fit_train, fit_train$test_data)
```

# PLS for IGIIR

```{r igiir}
fit_train <- project_data %>%
    analyze_pls(y = 'lIGIIR')

summary(fit_train)
validationplot(fit_train, newdata = fit_train$test_data)
predplot(fit_train, ncomp = c(1,2), newdata = fit_train$test_data)
plot_pls(fit_train)
calc_pred_corr(fit_train, fit_train$test_data)
```

# PLS for ISSI2

```{r issi2}
fit_train <- project_data %>%
    analyze_pls(y = 'lISSI2')

summary(fit_train)
validationplot(fit_train, newdata = fit_train$test_data)
predplot(fit_train, ncomp = c(1,2), newdata = fit_train$test_data)
plot_pls(fit_train)
calc_pred_corr(fit_train, fit_train$test_data)
```
